"""Tests for the line-item harvest, the header extraction, and the reconciliation.

These run against `invoices/sample-invoice.pdf`, which is generated by
`tools/make_sample_invoice.py` and committed. Every value in it is invented.

The point of testing a geometry harvest is that the geometry is the fragile
part. A regex on a header string is easy to reason about; "which number in this
row is the unit price" depends on x-coordinates that change with any layout
change, and the failure mode is a plausible-looking wrong number rather than an
exception. These tests pin the extracted values so that a change in anchoring
shows up as a failure rather than as a quietly wrong CSV.

Run: python -m unittest discover -s tests -v
"""
import csv
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

SAMPLE_PDF = ROOT / "invoices" / "sample-invoice.pdf"
SAMPLE_LAYOUT = ROOT / "bizflow" / "layouts" / "it.sample-vendor.yml"
SAMPLE_TEMPLATES = ROOT / "templates"

# What the sample PDF actually says, and therefore what the harvest must return.
# Row order matches the PDF. EAN prefixes 800..839 are the GS1 in-store test
# range, so these are not real trade items.
EXPECTED_ROWS = [
    # code,          qty, mpl, price, total,    piece_price
    ("8000000000017", 12, 6, 0.84, 60.14, 0.84),
    ("8000000000024", 24, 12, 0.20, 57.97, 0.20),
    ("8000000000031", 6, 6, 1.15, 41.30, 1.15),
    ("8000000000048", 4, 2, 9.25, 74.02, 9.25),
    ("8000000000055", 30, 10, 0.15, 43.59, 0.15),
    ("8000000000062", 12, 6, 0.95, 68.52, 0.95),
    ("8000000000079", 40, 12, 0.03, 14.06, 0.03),
    ("8000000000086", 8, 4, 0.99, 31.62, 0.99),
]

# The total the sample prints. analyze must reproduce this from the line items.
DECLARED_TOTAL = 391.22


class SampleExists(unittest.TestCase):
    """Guard: every other test in this file is meaningless without it."""

    def test_sample_pdf_is_committed(self):
        self.assertTrue(SAMPLE_PDF.is_file(), f"missing {SAMPLE_PDF}")
        self.assertGreater(SAMPLE_PDF.stat().st_size, 0)

    def test_sample_pdf_is_flagged_synthetic(self):
        """A leaked invoice would be a PDF without this line.

        Checked on the extracted text, not the raw bytes: the marker is drawn
        into a compressed content stream, so a byte search would not find it.
        What matters is that the text layer says so.
        """
        import pdfplumber

        with pdfplumber.open(SAMPLE_PDF) as pdf:
            text = "\n".join(page.extract_text() or "" for page in pdf.pages)
        self.assertIn("SYNTHETIC", text)


class Harvest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from bizflow.extract import harvest_items, load_layout

        cls.layout = load_layout(SAMPLE_LAYOUT)
        cls.items = harvest_items(SAMPLE_PDF, cls.layout)

    def test_every_row_is_found(self):
        self.assertEqual(len(self.items), len(EXPECTED_ROWS))

    def test_every_column_is_populated(self):
        """The failure this guards is a silently empty column.

        A missing column is worse than a crash: the CSV still looks like an
        invoice, and the analysis quietly reports on whatever survived.
        """
        for item in self.items:
            for col in ("code", "qty", "mpl", "price", "total", "piece_price"):
                self.assertIsNotNone(
                    item.get(col),
                    f"{item.get('code')} has no {col}",
                )

    def test_values_match_the_printed_document(self):
        for item, expected in zip(self.items, EXPECTED_ROWS):
            code, qty, mpl, price, total, piece = expected
            self.assertEqual(item["code"], code)
            self.assertEqual(item["qty"], qty)
            self.assertEqual(item["mpl"], mpl)
            self.assertAlmostEqual(item["price"], price, places=2)
            self.assertAlmostEqual(item["total"], total, places=2)
            self.assertAlmostEqual(item["piece_price"], piece, places=2)

    def test_description_is_recovered(self):
        first = self.items[0]["descrizione"]
        self.assertIn("caff", first)
        self.assertNotIn("1kg", first, "a unit suffix leaked into the description")

    def test_compound_header_is_anchored_on_its_last_word(self):
        """`P.zo Pz Imp.` and `P.zo Totale` share their first word.

        If either were anchored on the first word, the two columns would collide
        and the totals column would collect unit prices. The declared total below
        is the real assertion; this just names the mechanism.
        """
        totals = [i["total"] for i in self.items]
        units = [i["piece_price"] for i in self.items]
        self.assertNotEqual(totals, units)
        self.assertEqual(round(sum(totals), 2), DECLARED_TOTAL)


class Reconciliation(unittest.TestCase):
    """`analyze` exists to show printed-vs-full-precision; test that it does."""

    @classmethod
    def setUpClass(cls):
        import tempfile

        from bizflow.analyze import summarize
        from bizflow.extract import harvest_items, load_layout

        items = harvest_items(SAMPLE_PDF, load_layout(SAMPLE_LAYOUT))
        cls.tmp = tempfile.TemporaryDirectory()
        cls.csv = Path(cls.tmp.name) / "items.csv"
        with open(cls.csv, "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(items[0].keys()))
            w.writeheader()
            w.writerows(items)
        cls.summary = summarize(cls.csv)

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def test_printed_sum_reproduces_the_declared_total(self):
        self.assertAlmostEqual(self.summary["printed_sum"], DECLARED_TOTAL, places=2)

    def test_drift_is_present_and_small(self):
        """Rounding drift must be non-zero (that is the signal) but small.

        A drift of zero would mean the sample cannot demonstrate the feature; a
        large drift would mean the harvest is misreading a column, not that the
        supplier rounded.
        """
        drift = self.summary["full_precision_sum"] - self.summary["printed_sum"]
        self.assertNotAlmostEqual(drift, 0.0, places=2)
        self.assertLess(abs(drift), DECLARED_TOTAL * 0.01)


class Header(unittest.TestCase):
    def test_sample_template_extracts_every_field(self):
        from bizflow.extract import extract_header

        got = extract_header(SAMPLE_PDF, SAMPLE_TEMPLATES)
        self.assertIsNotNone(got, "no template matched the bundled sample")
        self.assertEqual(got["issuer"], "Sample Vendor S.r.l.")
        self.assertEqual(got["invoice_number"], "SAMPLE-0001")
        self.assertEqual(got["amount"], DECLARED_TOTAL)
        self.assertEqual(got["vat_number"], "IT00000000000")
        self.assertEqual(got["date"].strftime("%Y-%m-%d"), "2026-09-01")

    def test_no_match_returns_none_rather_than_raising(self):
        from bizflow.extract import extract_header

        # A directory with no templates: the documented no-match path.
        import tempfile

        with tempfile.TemporaryDirectory() as empty:
            self.assertIsNone(extract_header(SAMPLE_PDF, empty))


if __name__ == "__main__":
    unittest.main()
